### ISSUE TITLE
Multi-lined project name looks weird

### ISSUE THREAD

**Issue by brene** [graphcool/console#317]
![image](https://cloud.githubusercontent.com/assets/4989523/19781008/bae3d6a6-9c87-11e6-8390-7660dff898c4.png)

**Comment by timsuchanek** [comment]
@brene Thanks for reporting this!
Just talked to @julianbauer about this, the solution would be to show the project name only in one line, but on the hover effect automatically scroll in the rest of the project name from the right side.
Probably one can do that with a css only solution, something like:
```css
.child {
  &:hover {
    transform: translateX(calc(100% - 250px))
  }
}
```
Where `250px` is the width of the sidebar (which is fix) and `100%` the width of the project name.
